Reviews Created and Tested
maneki-nico/hiking-trail-app pull request #3
Opened 2022-11-02 20:24 UTC by jfresh560

Review migrations, model, controller, and tests created, associated with trails as a belongs_to, no styling no forms

2022-11-02 20:42 UTC, jfresh560 commented
Also components

2022-11-02 20:48 UTC, nwalberts requested changes

2022-11-02 20:48 UTC, nwalberts commented on app/controllers/api/v1/reviews_controller.rb
> +    end
this unfortunately will all need to be deleted. You should not be fetching the reviews individually when you could just add them to the response of your trails#show. See comment in that controller

2022-11-02 20:48 UTC, nwalberts commented on app/controllers/api/v1/trails_controller.rb
>          render json: trails
this should be just one line. Combine 4 and 6

2022-11-02 20:48 UTC, nwalberts commented on app/controllers/api/v1/trails_controller.rb
>          render json: trail
so, you are going to need to rework this a smidge by adding a TrailSerializer

that serializer should link reviews as well (see clinic), which will also mean you will want a ReviewSerializer

Once you have those, you wont need two fetch requests (one for trail, one for reviews) but instead one fetch request that can do both! faster and simpler

2022-11-02 20:48 UTC, nwalberts commented on app/javascript/react/components/ReviewTile.js
> +        </div>
this div is not doing anything. Delete it! 

now that we are in projects, we should no longer ever use `br` tags. Instead use CSS to get the intended spacing and alignment

2022-11-02 20:48 UTC, nwalberts commented on app/javascript/react/components/TrailShowContainer.js
> +            getReviews()
we will be deleting this in favor of getting reviews and the trail in one request

2022-11-02 20:48 UTC, nwalberts commented on config/routes.rb
> +        resources :reviews, only: [:index]
once done with the refactor, you will be deleting line 11

2022-11-02 20:48 UTC, nwalberts commented on config/routes.rb
> +      resources :reviews, only: [:index]
line 14 isnt being used. Delete it

2022-11-02 20:48 UTC, nwalberts commented on spec/features/controllers/api/v1/reviews_controller_spec.rb
> +        end
this entire test will unfortunately be deleted, but you will be taking some of this and doing the checks in the `trails_controller_spec.rb`

2022-11-03 19:40 UTC, jfresh560 commented
- SERIALIZERS MADE
- SECOND FETCH DELETED
- TEST FIXED, SECOND TEST DELETED
- ROUTES FIXED/DELETED
- CLEANED UP LOOSE DIVS

2022-11-03 19:58 UTC, dovakeen118 reviewed
this is looking good! the main change requested here is that a review belongs to a user. you don't necessarily need to display the user information with the review, but for accountability and metrics on the back end we'll want that info

2022-11-03 19:58 UTC, dovakeen118 commented on app/javascript/react/components/TrailShowContainer.js
> +                description={trail.description}
in the future you may decide to just pass `trail={trail)` rather than calling on each property individually here

2022-11-03 19:58 UTC, dovakeen118 commented on app/javascript/react/components/TrailShowContainer.js
> +    const [reviews, setReviews] = useState([])
instead of 2 separate pieces of state, you could defined the trail state as
```js
const [trails, setTrails] = useState({
  reviews: []
})
```

2022-11-03 19:58 UTC, dovakeen118 commented on app/serializers/review_serializer.rb
> +end
extra empty lines

2022-11-03 19:58 UTC, dovakeen118 commented on db/migrate/20221102173636_create_reviews.rb
> +      t.belongs_to :trail, null: false
we should set up reviews to be also associated with a user - you can display the reviews anonymously, but on the DB we should be tracking who made the review. this is common practice in the industry, and will set you up for potential future features such as editing or deleting reviews (which we want to make sure only the user who created that review can edit or delete it!)

2022-11-03 19:58 UTC, dovakeen118 commented on app/javascript/react/components/ReviewTile.js
> +        </div>
you may want to double check that this is formatting correctly with a single `div`, both pieces of information may appear on the same line on the page as opposed to how we see it here separated

2022-11-04 14:30 UTC, merged